### ISSUE TITLE
Documentation / Wiki

### ISSUE THREAD

**Issue by julevdl** [amosproj/amos2021ss02-project2-context-map#382]
## User story
1. As an IT project manager
2. I want / need to read a complete technical / build documentation
3. So that I can implement the software on my own device

## Acceptance criteria
* Complete build documentation
* Complete technical documentation 
* Make it understandable for first time users 

## Definition of done
* Documentation conform with tsdoc
* Reviewed with 4 eyes principle
* Understandable documentation for developers 
* did not break other code

**Comment by CatoLeanTruetschel** [comment]
I will add additional, more details technical descriptions to the wiki that is based on the technical presentation slides.
